part of '../media_item.dart';

/// Backend-tagged concrete subclass for items sourced from a Jellyfin
/// server. Carries only the backend-neutral fields — Plex-only fields
/// (trailerKey, audienceRating, etc.) live on [PlexMediaItem] instead.
final class JellyfinMediaItem extends MediaItem {
  /// Jellyfin per-playlist item id — only set when the item came out of
  /// `/Playlists/{id}/Items`. Used as the `entryIds` / move-target id for
  /// the playlist write endpoints. Null outside playlist contexts.
  final String? playlistItemId;

  const JellyfinMediaItem({
    required super.id,
    required super.kind,
    super.guid,
    super.title,
    super.titleSort,
    super.summary,
    super.tagline,
    super.originalTitle,
    super.studio,
    super.year,
    super.originallyAvailableAt,
    super.contentRating,
    super.parentId,
    super.parentTitle,
    super.parentThumbPath,
    super.parentIndex,
    super.index,
    super.grandparentId,
    super.grandparentTitle,
    super.grandparentThumbPath,
    super.grandparentArtPath,
    super.thumbPath,
    super.artPath,
    super.clearLogoPath,
    super.backgroundSquarePath,
    super.durationMs,
    super.viewOffsetMs,
    super.viewCount,
    super.lastViewedAt,
    super.leafCount,
    super.viewedLeafCount,
    super.childCount,
    super.addedAt,
    super.updatedAt,
    super.rating,
    super.userRating,
    super.genres,
    super.directors,
    super.writers,
    super.producers,
    super.countries,
    super.collections,
    super.labels,
    super.styles,
    super.moods,
    super.roles,
    super.mediaVersions,
    super.libraryId,
    super.libraryTitle,
    super.audioLanguage,
    this.playlistItemId,
    super.serverId,
    super.serverName,
    super.raw,
  }) : super._(backend: MediaBackend.jellyfin);

  /// Override the base [MediaItem.copyWith] so [playlistItemId] survives
  /// round-trips through the absolutizer (which calls copyWith to rewrite
  /// image paths). Without this, every Jellyfin playlist item came out with
  /// `playlistItemId == null` after mapping, making the move/remove endpoints
  /// silently no-op.
  @override
  JellyfinMediaItem copyWith({
    String? id,
    MediaBackend? backend,
    MediaKind? kind,
    String? guid,
    String? title,
    String? titleSort,
    String? summary,
    String? tagline,
    String? originalTitle,
    String? studio,
    int? year,
    String? originallyAvailableAt,
    String? contentRating,
    String? parentId,
    String? parentTitle,
    String? parentThumbPath,
    int? parentIndex,
    int? index,
    String? grandparentId,
    String? grandparentTitle,
    String? grandparentThumbPath,
    String? grandparentArtPath,
    String? thumbPath,
    String? artPath,
    String? clearLogoPath,
    String? backgroundSquarePath,
    int? durationMs,
    int? viewOffsetMs,
    int? viewCount,
    int? lastViewedAt,
    int? leafCount,
    int? viewedLeafCount,
    int? childCount,
    int? addedAt,
    int? updatedAt,
    double? rating,
    double? userRating,
    List<String>? genres,
    List<String>? directors,
    List<String>? writers,
    List<String>? producers,
    List<String>? countries,
    List<String>? collections,
    List<String>? labels,
    List<String>? styles,
    List<String>? moods,
    List<MediaRole>? roles,
    List<MediaVersion>? mediaVersions,
    String? libraryId,
    String? libraryTitle,
    String? audioLanguage,
    String? subtitleLanguage,
    int? subtitleMode,
    String? playlistItemId,
    String? serverId,
    String? serverName,
    Map<String, Object?>? raw,
  }) {
    return JellyfinMediaItem(
      id: id ?? this.id,
      kind: kind ?? this.kind,
      guid: guid ?? this.guid,
      title: title ?? this.title,
      titleSort: titleSort ?? this.titleSort,
      summary: summary ?? this.summary,
      tagline: tagline ?? this.tagline,
      originalTitle: originalTitle ?? this.originalTitle,
      studio: studio ?? this.studio,
      year: year ?? this.year,
      originallyAvailableAt: originallyAvailableAt ?? this.originallyAvailableAt,
      contentRating: contentRating ?? this.contentRating,
      parentId: parentId ?? this.parentId,
      parentTitle: parentTitle ?? this.parentTitle,
      parentThumbPath: parentThumbPath ?? this.parentThumbPath,
      parentIndex: parentIndex ?? this.parentIndex,
      index: index ?? this.index,
      grandparentId: grandparentId ?? this.grandparentId,
      grandparentTitle: grandparentTitle ?? this.grandparentTitle,
      grandparentThumbPath: grandparentThumbPath ?? this.grandparentThumbPath,
      grandparentArtPath: grandparentArtPath ?? this.grandparentArtPath,
      thumbPath: thumbPath ?? this.thumbPath,
      artPath: artPath ?? this.artPath,
      clearLogoPath: clearLogoPath ?? this.clearLogoPath,
      backgroundSquarePath: backgroundSquarePath ?? this.backgroundSquarePath,
      durationMs: durationMs ?? this.durationMs,
      viewOffsetMs: viewOffsetMs ?? this.viewOffsetMs,
      viewCount: viewCount ?? this.viewCount,
      lastViewedAt: lastViewedAt ?? this.lastViewedAt,
      leafCount: leafCount ?? this.leafCount,
      viewedLeafCount: viewedLeafCount ?? this.viewedLeafCount,
      childCount: childCount ?? this.childCount,
      addedAt: addedAt ?? this.addedAt,
      updatedAt: updatedAt ?? this.updatedAt,
      rating: rating ?? this.rating,
      userRating: userRating ?? this.userRating,
      genres: genres ?? this.genres,
      directors: directors ?? this.directors,
      writers: writers ?? this.writers,
      producers: producers ?? this.producers,
      countries: countries ?? this.countries,
      collections: collections ?? this.collections,
      labels: labels ?? this.labels,
      styles: styles ?? this.styles,
      moods: moods ?? this.moods,
      roles: roles ?? this.roles,
      mediaVersions: mediaVersions ?? this.mediaVersions,
      libraryId: libraryId ?? this.libraryId,
      libraryTitle: libraryTitle ?? this.libraryTitle,
      audioLanguage: audioLanguage ?? this.audioLanguage,
      playlistItemId: playlistItemId ?? this.playlistItemId,
      serverId: serverId ?? this.serverId,
      serverName: serverName ?? this.serverName,
      raw: raw ?? this.raw,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {...super.toJson(), if (playlistItemId != null) 'playlistItemId': playlistItemId};
  }

  /// Restore a [JellyfinMediaItem] from a [toJson] payload. Used as the
  /// non-Plex fallback by [MediaItem.fromJson].
  factory JellyfinMediaItem.fromJson(Map<String, dynamic> json) {
    final base = _parseBaseFields(json);
    return JellyfinMediaItem(
      id: base.id,
      kind: base.kind,
      guid: base.guid,
      title: base.title,
      titleSort: base.titleSort,
      summary: base.summary,
      tagline: base.tagline,
      originalTitle: base.originalTitle,
      studio: base.studio,
      year: base.year,
      originallyAvailableAt: base.originallyAvailableAt,
      contentRating: base.contentRating,
      parentId: base.parentId,
      parentTitle: base.parentTitle,
      parentThumbPath: base.parentThumbPath,
      parentIndex: base.parentIndex,
      index: base.index,
      grandparentId: base.grandparentId,
      grandparentTitle: base.grandparentTitle,
      grandparentThumbPath: base.grandparentThumbPath,
      grandparentArtPath: base.grandparentArtPath,
      thumbPath: base.thumbPath,
      artPath: base.artPath,
      clearLogoPath: base.clearLogoPath,
      backgroundSquarePath: base.backgroundSquarePath,
      durationMs: base.durationMs,
      viewOffsetMs: base.viewOffsetMs,
      viewCount: base.viewCount,
      lastViewedAt: base.lastViewedAt,
      leafCount: base.leafCount,
      viewedLeafCount: base.viewedLeafCount,
      childCount: base.childCount,
      addedAt: base.addedAt,
      updatedAt: base.updatedAt,
      rating: base.rating,
      userRating: base.userRating,
      genres: base.genres,
      directors: base.directors,
      writers: base.writers,
      producers: base.producers,
      countries: base.countries,
      collections: base.collections,
      labels: base.labels,
      styles: base.styles,
      moods: base.moods,
      roles: base.roles,
      mediaVersions: base.mediaVersions,
      libraryId: base.libraryId,
      libraryTitle: base.libraryTitle,
      audioLanguage: base.audioLanguage,
      playlistItemId: json['playlistItemId'] as String?,
      serverId: base.serverId,
      serverName: base.serverName,
      raw: base.raw,
    );
  }
}
